spring.application.name=trackticket

spring.datasource.url=jdbc:mysql://localhost:3306/trackticket
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

server.servlet.context-path=/api

ticketmaster.api.url = https://app.ticketmaster.com/discovery/v2
ticketmaster.api.key = uDn8Th1Hg0DWXaInqHaQ2gQ7s1VJ0Ru9

spotify.api.url = https://api.spotify.com/v1
spotify.token.url = https://accounts.spotify.com/api/token
spotify.client.id = 41002883abee4b4f8721d9b0fc13cbe5
spotify.client.secret = 935a926a691e4413a9f81b06d46d3b2e